/* ---------------- SUGGESTED QUESTIONS ---------------- */

export const suggestedQuestions = [
  "Tell me about yourself",
  "What is your UX design experience?",
  "What technologies do you specialize in?",
  "What projects have you worked on?",
  "What was your most challenging project?",
  "How do you approach UX research?",
  "How do you conduct usability testing?",
  "What is your UX design process?",
  "What is design thinking?",
  "How do you validate UX decisions?",
  "What is your experience with React?",
  "What is your front-end development experience?",
  "How do you improve performance in React applications?",
  "How do you ensure responsive design?",
  "How do you ensure accessibility in UI design?",
  "How do you handle API integrations?",
  "Which tools do you use for prototyping?",
  "How do you collaborate with developers?",
  "How do you handle design handoff to developers?",
  "What is your experience with design systems?",
  "How do you measure UX success?",
  "What industries have you worked in?",
  "How do you handle stakeholder feedback?",
  "What agile methodologies have you worked with?",
  "How do you stay updated with UX trends?",
  "What motivates you as a designer?",
  "Why should we hire you?",
  "Where can we see your portfolio?",
];
